name: manual approver

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.first.outputs.image }}
      tag: ${{ steps.first.outputs.tag }}
      name: ${{ steps.first.outputs.name }}
      

    steps:
      - name: checkout branch
        uses: actions/checkout@v3

      - name: run build
        id: first
        run: |
          echo "Building application"
          echo "Approve the request after build to deploy"
          echo "image=nginx" >> "$GITHUB_OUTPUT"
          echo "tag=v1.0.0" >> "$GITHUB_OUTPUT"
          echo "name=prod" >> "$GITHUB_OUTPUT"
          
      - name: using output from first step to second
        id: second
        run: |
          echo "${{steps.first.outputs.name}}"
          

  prod:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: Prod
      url: https://test.com

    steps:
      - name: deploy to prod
        env: 
          name: ${{ needs.build.outputs.name }}
        run: |
          echo "deploying to prodcution"
          echo "deploying ${{ needs.build.outputs.image}}:${{ needs.build.outputs.tag}}"
          echo "$name"
      - name: triggering workflow in devops repository
        env:
          image: "${{ needs.build.outputs.image}}:${{ needs.build.outputs.tag}}"
          environment: ${{ needs.build.outputs.name }}
        run: |
          curl -L \
            -X POST   \
            -H "Accept: application/vnd.github+json"  \
            -H "Authorization: Bearer ${{secret.PAT_TOKEN}}" \
            https://api.github.com/repos/pakuma1/devops/actions/workflows/main.yml/dispatches  \
             - d '{"ref": "main", "inputs": {"logLevel": "info", "image": $image, "environment": $environment}}'

    
      
