name: manual approver

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.first.outputs.image }}
      tag: ${{ steps.first.outputs.tag }}
      name: ${{ steps.first.outputs.name }}
      

    steps:
      - name: checkout branch
        uses: actions/checkout@v3

      - name: run build
        id: first
        run: |
          echo "Building application"
          echo "Approve the request after build to deploy"
          echo "image=nginx" >> "$GITHUB_OUTPUT"
          echo "tag=v1.0.0" >> "$GITHUB_OUTPUT"
          echo "name=prod" >> "$GITHUB_OUTPUT"
          

  prod:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: deploy to prod
        env: 
          name: ${{ needs.build.outputs.name }}
        run: |
          echo "deploying to prodcution"
          echo "deploying ${{ needs.build.outputs.image}}:${{ needs.build.outputs.tag}}"
          echo "$name"
        
    environment:
      name: Prod
      url: https://test.com
      
